################################################
# global configuration
#  more details: https://github.com/dmachard/go-dnscollector/blob/main/docs/configuration.md#global
################################################
global:
  trace:
    verbose: true
  server-identity: "dns-collector"
  pid-file: ""
  text-format: "timestamp-rfc3339ns identity operation rcode queryip queryport family protocol length-unit qname qtype edns-csubnet latency answer"
  text-format-delimiter: " "
  text-format-boundary: "\""
  text-jinja: ""
  worker:
    interval-monitor: 10
    buffer-size: 4096
  telemetry:
    enabled: true
    web-path: "/metrics"
    web-listen: ":9165"
    prometheus-prefix: "dnscollector_exporter"
    tls-support: false
    tls-cert-file: ""
    tls-key-file: ""
    client-ca-file: ""
    basic-auth-enable: false
    basic-auth-login: admin
    basic-auth-pwd: changeme

################################################
# Pipelining configuration
#   more details: https://github.com/dmachard/go-dnscollector/blob/main/docs/running_mode.md#pipelining
#   workers: https://github.com/dmachard/go-dnscollector/blob/main/docs/workers.md
#   transformers: https://github.com/dmachard/go-dnscollector/blob/main/docs/transformers.md
################################################
pipelines:

  - name: powerdns
    powerdns:
      listen-ip: 127.0.0.1
      listen-port: 6001
      tls-support: false
      tls-min-version: 1.2
      cert-file: ""
      key-file: ""
      reset-conn: true
      chan-buffer-size: 0
      add-dns-payload: true
    routing-policy:
      forward: [ console ]
      dropped: [ ]

  - name: tap
    dnstap:
      listen-ip: 127.0.0.1
      listen-port: 6000
    transforms:
      normalize:
        qname-lowercase: true
        qname-replace-nonprintable: true
    routing-policy:
      forward: [ elastic ]
      dropped: [ ]

  - name: console
    stdout:
      mode: json

  - name: elastic
    elasticsearch:
      server: "https://elasticsearch.infra.example.com/"
      index:  "dnscollector"
      chan-buffer-size: 0
      bulk-size: 1000000 # 1MB
      flush-interval: 10 # in seconds
      compression: none
      bulk-channel-size: 10
      basic-auth-enable: true
      basic-auth-login: ingester
      basic-auth-pwd: changeme
      curl-tracing-enable: false
